export default {
    CHANGE_LABEL_ITEM:'CHANGE_LABEL_ITEM',
    ADD_FALL_LIST:"ADD_FALL_LIST",
    ADD_VIP_HOME_CHEDULAR:'ADD_VIP_HOME_CHEDULAR',
    ADD_HOME_BANNER:'ADD_HOME_BANNER',
    ADD_HOSTS_SHOW_LIST:'ADD_HOSTS_SHOW_LIST',
    ADD_POSTPONE_SHOW:"ADD_POSTPONE_SHOW"
}